"""empty message

Revision ID: 539cef83c9c4
Revises: 615c9645b9e3
Create Date: 2020-12-22 14:04:41.752223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '539cef83c9c4'
down_revision = '615c9645b9e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('modify_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('modify_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
